### ISSUE TITLE
Crashed when there are too many lines from Telegram

### ISSUE THREAD

**Issue by caasi** [caasi/teleirc#3]
sample input:

```
descend sung, [23.03.17 23:33]
.file  "a.c"
  .text
  .globl  swit
  .type  swit, @function
swit:
  pushq  %rbp
  movq  %rsp, %rbp
  movl  %edi, -4(%rbp)
  movl  -4(%rbp), %eax
  subl  $161, %eax
  cmpl  $36, %eax
  ja  .L2
  movl  %eax, %eax
  movq  .L4(,%rax,8), %rax
  jmp  *%rax
  .section  .rodata
  .align 8
  .align 4
.L4:
  .quad  .L3
  .quad  .L3
  .quad  .L3
  .quad  .L3
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L3
  .quad  .L3
  .quad  .L3
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L2
  .quad  .L3
  .text
.L3:
  movl  $0, %eax
  jmp  .L5
.L2:
  movl  $-1, %eax
.L5:
  popq  %rbp
  ret
  .size  swit, .-swit
  .globl  main
  .type  main, @function
main:
  pushq  %rbp
  movq  %rsp, %rbp
  subq  $16, %rsp
  movl  %edi, -4(%rbp)
  movq  %rsi, -16(%rbp)
  movl  $180, %edi
  call  swit
  movl  $0, %eax
  leave
  ret
  .size  main, .-main
  .ident  "GCC: (GNU) 5.4.0"
  .section  .note.GNU-stack,"",@progbits
```

**Comment by caasi** [comment]
應該是爛在這行， `this.conn` 空掉了： https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L936

**Comment by caasi** [comment]
descend 又提供了更短的測資：

```
class now_time
{
};

int main(int argc, char *argv[])
{
  int now_time;
  now_time my_time;
  
  return 0;
}
descent@debian64:tmp$ g++ a.cpp 
a.cpp: In function 'int main(int, char**)':
a.cpp:8:12: error: expected ';' before 'my_time'
   now_time my_time;
```

死在一樣的地方。

**Comment by caasi** [comment]
```
5: movl %esp, %ebp
n: movl
n: %esp
n: %ebp
```

`n: %ebp` 還沒出來， bot 就掛了 XD

**Comment by caasi** [comment]
noed-irc 還會因為別的原因空掉 :(

```
/home/caasi/GitHub/teleirc/node_modules/irc/lib/irc.js:936
    if (!this.conn.requestedDisconnect) {
                  ^

TypeError: Cannot read property 'requestedDisconnect' of null 
    at Client.send (/home/caasi/GitHub/teleirc/node_modules/irc/lib/irc.js:936:19)
    at Timeout.dequeue (/home/caasi/GitHub/teleirc/node_modules/irc/lib/irc.js:966:22)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by caasi** [comment]
更多來自 descent 的測資，一樣無法 100% 搞爛 bot ：

```
已經進入 long mode, 使用 page, 一核心, 所以 gdt 已經被設定了, 在 qemu 中, 是以下的內容:



gdt: 47, addr: 07ED6F18
0: 0 0
8: CF9200 FFFF
10: CF9F00 FFFF
18: CF9300 FFFF
20: CF9A00 FFFF
28: 0 0
30: CF9300 FFFF
38: AF9A00 FFFF
40: 0 0


uefi 挑 0x38 為 cs selector。
```

**Comment by caasi** [comment]
上游從 [4f26402](https://github.com/FruitieX/teleirc/commit/4f26402e966a3e0f23b9b64facbc1610af0cbf1b) 開始，捨 `node-irc` 改用 `irc-framework`，先關掉這個 issue ，觀察看看。
