### ISSUE TITLE
Other errors

### ISSUE THREAD

**Issue by caasi** [caasi/teleirc#6]
This thread collects other errors that cause the bot to restart itself:

```
error:  Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities in message text: Unsupported start tag \"\" at byte offset 80"}
    at /home/caasi/GitHub/teleirc/node_modules/node-telegram-bot-api/src/telegram.js:136:15
    at tryCatcher (/home/caasi/GitHub/teleirc/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/caasi/GitHub/teleirc/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/caasi/GitHub/teleirc/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/caasi/GitHub/teleirc/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/caasi/GitHub/teleirc/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/caasi/GitHub/teleirc/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/caasi/GitHub/teleirc/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by caasi** [comment]
古老的 bug 先關掉。
